language: node_js
node_js:
  - "node"
cache: yarn
env:
  global:
    - NODE_ENV=production
    - AWS_DEFAULT_REGION=eu-central-1

install:
  # aws cli
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - export PATH=~/bin:$PATH

  # yarn + dependencies
  - npm install yarn -g
  - yarn install --production=false

script:
  - yarn build

after_success:
  - aws s3 sync build s3://dietenberger-website --delete
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"